### ISSUE TITLE
Unhandled Error - cleaner is unable to access the file path

### ISSUE THREAD

**Issue by SteloPin** [stojy/ClrVpin#60] opened 2023-04-07 16:45 UTC
**Describe the bug**<br />[A description of the bug]<br /><br />**To Reproduce**<br />[Steps to reproduce the bug]<br /><br />**Expected behavior**<br />[If applicable, what did you expect to happen]<br /><br />**Screenshots**<br />[If applicable, add screenshots]<br /><br />**Logs**<br />[If applicable, add the log file (or relevant snippet): c:\ProgramData\ClrVpin\logs\ClrVpin.log]<br /><br />**Unhandled Error Details**<br /><pre>Message:       Could not find a part of the path.<br />Inner Message: <br />Assembly:      ClrVpin, Version=7.0.1.0, Culture=neutral, PublicKeyToken=null<br />Sender:        System.Windows.Threading.Dispatcher<br />Source:        Application.Current.DispatcherUnhandledException<br />Stack:<br />   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)<br />   at ClrVpin.Shared.FileUtils.Rename(String sourcePath, String destinationPath) in D:\a\ClrVpin\ClrVpin\ClrVpin\Shared\FileUtils.cs:line 290<br />   at ClrVpin.Shared.FileUtils.Rename(Hit hit, LocalGame localGame, ICollection\`1 supportedHitTypes, IEnumerable\`1 kindredExtensions) in D:\a\ClrVpin\ClrVpin\ClrVpin\Shared\FileUtils.cs:line 86<br />   at ClrVpin.Cleaner.CleanerUtils.FixOrderedHits(ICollection\`1 orderedHits, List\`1 gameFiles, LocalGame localGame) in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 140<br />   at ClrVpin.Cleaner.CleanerUtils.<>c__DisplayClass2_3.<Fix>b__7(LocalGame fixableContentLocalGame) in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 88<br />   at System.Collections.Generic.List\`1.ForEach(Action\`1 action)<br />   at ClrVpin.Cleaner.CleanerUtils.<>c__DisplayClass2_0.<Fix>b__2(ContentType contentType) in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 59<br />   at System.Collections.Generic.List\`1.ForEach(Action\`1 action)<br />   at ClrVpin.Cleaner.CleanerUtils.Fix(ICollection\`1 localGames, String backupFolder, Action\`2 updateProgress) in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 48<br />   at ClrVpin.Cleaner.CleanerUtils.<>c__DisplayClass1_0.<FixAsync>b__0() in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 22<br />   at System.Threading.Tasks.Task\`1.InnerInvoke()<br />   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)<br />   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)<br />--- End of stack trace from previous location ---<br />   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)<br />   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task

**Comment by stojy** [comment] 2023-04-09 03:26
hi @SteloPin, sorry to hear you're having issues.

The problem you're seeing is happening when the file is being renamed.  Looking online, the most common cause appears to be either..
- Folder + file name exceeds Windows 255 char limit.
- Folder has a trailing space.

Neither of these should be an issue though if you're running a 'modern' windows OS as the .Net version used by ClrVpin automatically works around both of these limitations.  I've tested both those scenarios on my Windows 10 box and it works fine.  Perhaps you're running an older Windows OS which doesn't support long folder names?  Or perhaps it's something unrelated (e.g. network drive, mapped folder, etc)?

In any event, it should be an easy fix (or at least display a warning dialog instead of an unhandled error).  Can you please attach your log file (typically located here.. c:\ProgramData\ClrVpin\logs\ClrVpin.log) so I can be sure of the root cause.

Also, if there's any special instructions/repro steps be sure to add them to the issue description.

**Comment by stojy** [comment] 2023-04-26 13:55
hi @SteloPin, just checking in to see if you wanted me to pursue this posible bug?  I'll need the log file and (ideally) some steps to repro.

If not, I'll close out the issue.

**Comment by SteloPin** [comment] 2023-04-28 11:14
Hi stoj,

I‘m sorry but I have very little time to do more debugging.
I have linked folders in my PinballX-Folders. That is maybe the problem.

Thank you for your effort to develop the whole thing!

Have a nice day,
Stefan


stoj ***@***.***> schrieb am Mi. 26. Apr. 2023 um 15:55:

**Comment by stojy** [comment] 2023-04-30 10:54
No worries @SteloPin.  I've tried a few more things to get a repro without any success..
- setup a linked folder
- setup a network folder
- access network folder via mapped drive

Which makes me think the issue you've got is caused by an older OS (or an unusual linked folder configuraiton) that doesn't support long folder names.

However, I did manage to create a related issue where it fails to handle a network folder that is readonly.  So I've added some special handling for that which _perhaps_ might fix your issue too.

Going forward..
- Please update to 7.2.0 (or later) which includes the above fix.
- I'll close this issue out.
- If it happens again then let ClrVpin v7.2.0 submit a new bug as this will include the extra information needed.. i.e. last few clrvpin log entries and some basic system info.

Thanks

**Closed by stojy** 2023-04-30 10:54 UTC

**Comment by SteloPin** [comment] 2023-04-30 22:37
Thank you for your effort to make ClrVpin more stable in unusual
konfigurations! I will try it out.
Thanks,
Stefan

stoj ***@***.***> schrieb am So. 30. Apr. 2023 um 12:54:
