### ISSUE TITLE
Unhandled Error - [add summary description here]

### ISSUE THREAD

**Issue by SteloPin** [stojy/ClrVpin#61] opened 2023-04-07 16:59 UTC
**Describe the bug**<br />[A description of the bug]<br /><br />**To Reproduce**<br />[Steps to reproduce the bug]<br /><br />**Expected behavior**<br />[If applicable, what did you expect to happen]<br /><br />**Screenshots**<br />[If applicable, add screenshots]<br /><br />**Logs**<br />[If applicable, add the log file (or relevant snippet): c:\ProgramData\ClrVpin\logs\ClrVpin.log]<br /><br />**Unhandled Error Details**<br /><pre>Message:       Could not find a part of the path.<br />Inner Message: <br />Assembly:      ClrVpin, Version=7.0.1.0, Culture=neutral, PublicKeyToken=null<br />Sender:        System.Windows.Threading.Dispatcher<br />Source:        Application.Current.DispatcherUnhandledException<br />Stack:<br />   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)<br />   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)<br />   at ClrVpin.Shared.FileUtils.Rename(String sourcePath, String destinationPath) in D:\a\ClrVpin\ClrVpin\ClrVpin\Shared\FileUtils.cs:line 298<br />   at ClrVpin.Shared.FileUtils.Rename(String sourcePath, String newPath, HitTypeEnum hitTypeEnum, String contentType, Action\`1 backupAction) in D:\a\ClrVpin\ClrVpin\ClrVpin\Shared\FileUtils.cs:line 179<br />   at ClrVpin.Shared.FileUtils.Rename(Hit hit, LocalGame localGame, ICollection\`1 supportedHitTypes, IEnumerable\`1 kindredExtensions) in D:\a\ClrVpin\ClrVpin\ClrVpin\Shared\FileUtils.cs:line 80<br />   at ClrVpin.Cleaner.CleanerUtils.FixOrderedHits(ICollection\`1 orderedHits, List\`1 gameFiles, LocalGame localGame) in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 154<br />   at ClrVpin.Cleaner.CleanerUtils.<>c__DisplayClass2_3.<Fix>b__7(LocalGame fixableContentLocalGame) in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 91<br />   at System.Collections.Generic.List\`1.ForEach(Action\`1 action)<br />   at ClrVpin.Cleaner.CleanerUtils.<>c__DisplayClass2_0.<Fix>b__2(ContentType contentType) in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 59<br />   at System.Collections.Generic.List\`1.ForEach(Action\`1 action)<br />   at ClrVpin.Cleaner.CleanerUtils.Fix(ICollection\`1 localGames, String backupFolder, Action\`2 updateProgress) in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 48<br />   at ClrVpin.Cleaner.CleanerUtils.<>c__DisplayClass1_0.<FixAsync>b__0() in D:\a\ClrVpin\ClrVpin\ClrVpin\Cleaner\CleanerUtils.cs:line 22<br />   at System.Threading.Tasks.Task\`1.InnerInvoke()<br />   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)<br />   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)<br />--- End of stack trace from previous location ---<br />   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)<br />   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task

**Comment by stojy** [comment] 2023-04-09 03:15
closing as this appears to be a duplicate of #60

**Closed by stojy** 2023-04-09 03:15 UTC
